name: "Latest tag"
description: Automatically generate & update a 'latest' tag for your releases

runs:
  using: "node12"
  main: "lib/index.js"

branding:
  icon: tag
  color: blue

inputs:
  description:
    description: "Tag description"
    required: false
  tag-name:
    description: "Tag name that will be created or updated"
    required: false
