name: 'Latest tag'
description: Automatically generate & update a 'latest' tag for your releases

inputs:
  description:
    description: 'Tag description'
    required: false
  tag-name:
    description: 'Tag name'
    required: false
    default: latest
  force-branch:
    description: 'Force-update a branch rather than a tag'
    required: false
    default: 'false'

runs:
  using: 'node12'
  main: 'lib/index.js'

branding:
  icon: tag
  color: blue
