name: Build action
on:
  push:
    paths:
      - src/**
      - package.json
      - package-lock.json
      - .github/workflows/build.yml

jobs:
  build:
    name: Build with @zeit/ncc
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: npm i
      - run: npm run build
      - uses: EndBug/add-and-commit@v9
        with:
          add: lib --force
          message: '[auto] Update build'
